# site settings
title: Eaze
subtitle: at the University of Kansas
landing-title: Eaze
email: paul.negedu@yahoo.com
description: Allways wanting food. Russian blue kitty scratches couch bad kitty. Unwrap toilet paper. Cats making all the muffins ask for petting for cats go for world domination, lie on your belly and purr when you are asleep kick up litter but has closed eyes but still sees you. 
bg_img: assets/images/bg.jpg
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://localhost:4000" # the base hostname & protocol for your site
url: "https://humble-canyon.cloudvent.net/" # the base hostname & protocol for your site
author:
street_address: 4419 Adam Avenue
city: Lawrence
state: KS
zip_code: 66047
country: United States of America
phone: 

# social settings
500px_url:
facebook_url: https://facebook.com
github_url: 
gitlab_url: 
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com

# build settings
markdown: kramdown
highlighter: true

#Static Files
defaults:
  - scope:
      path: assets/images/shifts
    values:
      shift-image: true
  - scope:
      path: assets/images/thumbs/shifts
    values:
      shift-thumbnail: true
  - scope:
      path: assets/images/thumbs/dining
    values:
      dining-thumbnail: true
  - scope:
      path: assets/images/dining
    values:
      dining-image: true

#Plugins
plugins: [jekyll-paginate]

#Paginate
paginate: 6
paginate_path: /newsletter/page:num/

sass:
  style: compressed
